# -*- coding: utf-8 -*-
"""textcloud.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s8nyKHOZOvWpVGYXaH-MjGaodnPqR-TP

installing worldcloud and wikipedia for information
"""

!pip install wordcloud

!pip install wikipedia

"""import wiki for search item using wikipedia.page method"""

import wikipedia

result= wikipedia.page("Statistics")
final_result = result.content
final_result

"""to undestand and simplify  process adding sentence"""

result= wikipedia.summary("Statistics", sentences=6)
result

from wordcloud import WordCloud
from nltk.corpus import stopwords
import matplotlib.pyplot as plt

def plot_cloud(wordcloud):
    plt.figure(figsize=(10, 10))
    plt.imshow(wordcloud) 
    plt.axis("off");

wordcloud = WordCloud(width = 500, height = 500, background_color='pink', random_state=10).generate(final_result)
plot_cloud(wordcloud)

"""from this you can see statistical, sample and statistic are most used word"""